[build-system]
requires = [
  "importlib_resources~=3.0; python_version < '3.7'",
  "pip~=20.2",
  "setuptools~=49.6",
  "wheel~=0.35",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py36", "py37", "py38"]
include = '\.pyi?$'
exclude = '\.(git|mypy_cache|env)'

[tool.pytest.ini_options]
addopts = "-v --mypy"
testpaths = [
  "tests",
]
